module.exports={
	hl:{style:{color:"red"}}
	,link:{style:{textDecorationLine:"underline",
	textDecorationColor:"blue",textDecorationStyle:"double"}}
	,synonym:{style:{textDecorationLine:"underline",
	textDecorationColor:"brown",textDecorationStyle:"solid"}}	
		,synonym2:{style:{textDecorationLine:"underline",
	textDecorationColor:"brown",textDecorationStyle:"dotted"}}	
};